global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cryptolake-api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
